export const TRADE_SLUGS: Record<string, string> = {
  'air-conditioning':       'Air Conditioning',
  'bathroom-renovation':    'Bathroom Renovation',
  'blinds-curtains':        'Blinds & Curtains',
  'brick-layer':            'Brick Layer',
  'carpenter':              'Carpenter',
  'cctv-intercom':          'CCTV & Intercom',
  'ceiling':                'Ceiling',
  'cleaner':                'Cleaner',
  'domestic-worker':        'Domestic Worker',
  'drain-cleaning':         'Drain Cleaning',
  'electrician':            'Electrician',
  'flooring':               'Flooring',
  'gardener':               'Gardener',
  'handyman':               'Handyman',
  'garage-door-specialist': 'Garage Door Specialist',
  'glass-specialist':       'Glass Specialist',
  'it-specialist':          'IT Specialist',
  'kitchen-installer':      'Kitchen Installer',
  'landscaping':            'Landscaping',
  'mechanic':               'Mechanic',
  'moving-transport':       'Moving & Transport',
  'painter':                'Painter',
  'panel-beater':           'Panel Beater',
  'paving':                 'Paving',
  'pest-control':           'Pest Control',
  'plastering':             'Plastering',
  'plumber':                'Plumber',
  'pool-spa':               'Pool & Spa',
  'roofing':                'Roofing',
  'rubble-removal':         'Rubble Removal',
  'security':               'Security',
  'solar-installation':     'Solar Installation',
  'tiler':                  'Tiler',
  'tree-felling':           'Tree Felling',
  'waterproofing':          'Waterproofing',
  'welding':                'Welding',
}

export const AREA_SLUGS: Record<string, string> = {
  'johannesburg':     'Johannesburg',
  'cape-town':        'Cape Town',
  'durban':           'Durban',
  'pretoria':         'Pretoria',
  'port-elizabeth':   'Port Elizabeth',
  'east-london':      'East London',
  'bloemfontein':     'Bloemfontein',
  'nelspruit':        'Nelspruit',
  'polokwane':        'Polokwane',
  'kimberley':        'Kimberley',
  'rustenburg':       'Rustenburg',
  'pietermaritzburg': 'Pietermaritzburg',
  'witbank':          'Witbank',
  'centurion':        'Centurion',
  'soweto':           'Soweto',
}

// Top 10 trades for the /find/[trade]/[area] matrix (150 static pages)
export const TOP_TRADE_SLUGS = [
  'painter', 'plumber', 'electrician', 'cleaner', 'gardener',
  'handyman', 'tiler', 'carpenter', 'domestic-worker', 'roofing',
]
